FROM node:20-slim

WORKDIR /app

# Copy package management parameters
COPY frontend/package.json .

# Install node dependencies
RUN npm install

# Copy application files
COPY frontend /app/frontend

WORKDIR /app/frontend

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]
